name: CheckFlow Style
on: push

jobs:
  check-style:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install tools
        run: python -m pip install --upgrade pip pycodestyle
             python -m pip install --upgrade pip pytest
             pip3 install flask
             pip3 install flask-wtf
             pip3 install flask-sqlalchemy
             pip3 install email-validator
             pip3 install flask_behind_proxy


      - name: Check Style
        run: pycodestyle --first *.py

      - name: Test with pytest  # This is new!
        run: |
          python3 -m unittest tests/test_basic.py